### ISSUE TITLE
Failed to build DependencyGraph

### ISSUE THREAD

**Issue by lyc152** [huanxsd/MeiTuan#1]
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/petter/Documents/workspace/private/react-native-action/MeiTuan/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/petter/Documents/workspace/private/react-native-action/MeiTuan/node_modules/react-native-router-flux/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons

**Comment by terryc129** [comment]
same issue when using react-native start

**Comment by AdamChrist** [comment]
+1

**Comment by huanxsd** [comment]
I have changed the package, should be able to solve this problem.
Please let me know, if still fail.thanks

**Comment by terryc129** [comment]
@huanxsd solved. Thanks!
