### ISSUE TITLE
这个是什么语法？

### ISSUE THREAD

**Issue by immrss** [huanxsd/MeiTuan#12]
`class SearchBar extends PureComponent {
    props: {
        onSubmitEditing: Function,
        text: string,
        onChangeText: Function,
        onSubmit: Function,
        style: Object
    }
    state: {
        text: string
    }
`
props和 state这个是什么意思  是es6的语法吗？

**Comment by huanxsd** [comment]
issue只回答bug和建议，
RN问题移步官网（http://facebook.github.io/react-native/docs/getting-started.html）
