### ISSUE TITLE
移植问题

### ISSUE THREAD

**Issue by lihangyu89** [huanxsd/MeiTuan#13]
hello，我把你项目的src目录的所有文件拷贝到我自己init的项目中，打包时报错。。。
![image](https://user-images.githubusercontent.com/28355799/29748741-150ddc6a-8b4f-11e7-8afb-a319bb939179.png)
图片文件夹需要额外配置吗？

**Comment by huanxsd** [comment]
没遇到过这种错误，感觉像是你的工程不支持require引用图片的语法
