### ISSUE TITLE
请问这么写有什么用

### ISSUE THREAD

**Issue by qhhuang** [huanxsd/MeiTuan#15]
HomeMenuView line:47

let menuViews = []
        let pageCount = Math.ceil(menuItems.length / 10)

        for (let i = 0; i < pageCount; i++) {
            let length = menuItems.length < (i * 10) ? menuItems.length - (i * 10) : 10
            let items = menuItems.slice(i * 10, i * 10 + length)

....
这里的 length 不是一直都是10吗

**Comment by longlong-2l** [comment]
个人理解，这么做是为了让每一页最多显示10个标签，不足10时显示所有标签，当标签数量大于10时，pageCount的数量大于1，所以会筛选出10个为一组，剩下的单独一组，我也是刚学，而且代码还是两个星期前看的。

**Comment by qhhuang** [comment]
当标签数量大于10时，pageCount的数量大于1，所以会筛选出10个为一组，剩下的单独一组  的length也是10, 所以你直接写死length=10就好了呀, 要不你前面判断完了后面剩下的那一组也判断下 要不会很怪..

**Comment by longlong-2l** [comment]
如果起始的标签数量小于10，即menuItems.length小于10，那你length写死10，不就不对了。剩下的单独一组的length怎么一定会是10呢？

**Comment by qhhuang** [comment]
我的意思是 你的  表达式中 menuItems.length < (i * 10) ? menuItems.length - (i * 10) : 10 ,  menuItems.length 永远都大于  (i * 10)

**Comment by longlong-2l** [comment]
不好意思，仔细看了一下代码，真的是这样，而且程序跑了一下，写死10也没影响，之前没仔细看，“<” 当“>”看的，话说这个项目已经几个月没维护了。

**Comment by qhhuang** [comment]
我也是刚开始学-..-   你是学完了嘛 或者有没有什么好的RN项目推荐下

**Comment by huanxsd** [comment]
这里正好是等于10，因为外部传入的是20个。如果传入非10的整数，写死10，就会有问题了

**Comment by huanxsd** [comment]
感谢反馈，代码是有两个问题
1、长度计算不正确，其实应该这样
```
let length = menuItems.length < ((i + 1) * 10) ? menuItems.length - (i * 10) : 10
```
2、slice的第二个参数，即使越界了，也不会出错。如果在iOS中NSArray越界，就直接崩溃了。

**Comment by huanxsd** [comment]
所以这两种写法都可以
```
            let length = menuItems.length < ((i + 1) * 10) ? menuItems.length - (i * 10) : 10
            let items = menuItems.slice(i * 10, i * 10 + length)
```
或者
```
            let items = menuItems.slice(i * 10, i * 10 + 10)
```
