### ISSUE TITLE
react-native run-ios 报错

### ISSUE THREAD

**Issue by ytxbnahn** [huanxsd/MeiTuan#17]
终端显示 BUILD SUCCEEDED
模拟器
![image](https://user-images.githubusercontent.com/21984349/33360013-b2c00850-d50c-11e7-98f1-e8e9c9999f98.png)

**Comment by wangxu19910204** [comment]
node 服务没起，执行npm start

**Comment by huanxsd** [comment]
同上，看下是否能够解决
