### ISSUE TITLE
安装后运行报错 can't find valiable :process(http://10.0.3.2:8081....

### ISSUE THREAD

**Issue by njgaoqing** [huanxsd/MeiTuan#18]
用手机是可以运行的，genymotion模拟器不行

**Comment by njgaoqing** [comment]
下载 安装项目后，我是用npm install ，默认package.json的依赖库的版本有变动（但是没有体现在文件中）， 改变其中的react, react-native版本还是有问题；
使用 yarn install 问题解决。

**Comment by cxmmxc** [comment]
卧槽，解决了我的问题。我搞了一下午！！谢谢
