### ISSUE TITLE
eactNativeJS: undefined is not an object (evaluating 'o.View.propTypes.style')

### ISSUE THREAD

**Issue by mokinzhao** [huanxsd/MeiTuan#21]
eactNativeJS: undefined is not an object (evaluating 'o.View.propTypes.style')
12-28 14:20:51.598 23959-24073/com.meituan E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by mokinzhao** [comment]
打离线包后就遇到这样问题

**Comment by huanxsd** [comment]
看下是否有代码使用了
```
PropTypes
```
但是没有引用
```
import PropTypes from 'prop-types'
```

**Comment by huanxsd** [comment]
没有更多错误信息，暂时关闭issue。如果有更多信息提供，欢迎随时开启issue
