### ISSUE TITLE
我不清楚是我这边的环境问题,还是你这边的问题

### ISSUE THREAD

**Issue by JiaLiangoooo** [huanxsd/MeiTuan#22]
Develop菜单->Debug JS Remotely  -Reload 会报错
Runtime is not ready for debuging.
- Make sure Packger....
- Make sure the JavaScripte Debugger......

**Comment by chookg** [comment]
如果拔掉数据线以后，设置Debug server host & port for device 了么

**Comment by huanxsd** [comment]
可能是你的debug环境有问题，看下其他项目是否正常。因为没有提供具体报错信息，不好排查。

**Comment by huanxsd** [comment]
没有更多错误信息，暂时关闭issue。如果有更多信息提供，欢迎随时开启issue
