### ISSUE TITLE
run-android 没有结果

### ISSUE THREAD

**Issue by lbcsy** [huanxsd/MeiTuan#24]
我运行 react-native run-android, 屏幕止步于下面的屏幕拷贝，什么也没有：
Scanning folders for symlinks in C:\MyDev\Meituan\node_modules (69ms)
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running Metro Bundler on port 8081.                                       │
 │                                                                            │
 │  Keep Metro Bundler running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own Metro Bundler  instance if you    │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   C:\MyDev\Meituan

Metro Bundler ready.

Loading dependency graph, done.

**Comment by huanxsd** [comment]
这是已经正常启动了service
react native项目运行常见问题可以参考这里
http://facebook.github.io/react-native/docs/troubleshooting.html#content
