### ISSUE TITLE
能请问下弃用react-native-router-flux的具体原因是什么吗, flux内部不是基于react-navigation封装的吗, 我最开始使用react-navigation时返回到指定页面还是用router id的, 很不方便, 虽然现在也支持用router name了

### ISSUE THREAD

**Issue by NiuYangYang** [huanxsd/MeiTuan#31]
App的页面跳转、TabBar、Navigation，全部通过react-navigation实现。这是一个非常牛逼的库，可以实现很多自定义的跳转功能。最早是通过react-native-router-flux实现跳转。在遇见react-navigation后，我果断放弃了react-native-router-flux。

**Comment by huanxsd** [comment]
因为个人更喜欢用react-navigation的api风格。
然后从风险上考虑，react-navigation的star数更多，也是RN官方推荐的导航控制器控件。所以当时选了react-navigation

**Comment by NiuYangYang** [comment]
👌明白
