### ISSUE TITLE
react-native-router-flux 是不是不支持 react-native 0.44.0 ?

### ISSUE THREAD

**Issue by hama** [huanxsd/MeiTuan#6]
react-native-router-flux 是不是不支持 react-native 0.44.0 ?

**Comment by eppen** [comment]
最新版的route-flux跟rn0.44版本可能有冲突

安装route-flux的时候指定版本@0.38

hama <notifications@github.com>于2017年5月9日周二 18:19写道：

**Comment by hama** [comment]
我在 package.json  指定了 0.38 还是不行。总是生成 node_modules/react-native/node_modules/ ，不删掉，就会提示冲突。删掉又会提示有东西找不到

**Comment by huanxsd** [comment]
之前有出现过react-native-router-flux和react-native版本不兼容的情况。当时是通过写死react-native-router-flux版本号解决的。
前两天我把react-native-router-flux去掉了，用react-navigation代替。个人觉得react-navigation比react-native-router-flux好用。
建议clone最新的代码，重新npm install试下。

**Comment by eppen** [comment]
npm i react-native-router-flux@3.38.0 --save

2017-05-09 18:33 GMT+08:00 hama <notifications@github.com>:

**Comment by eppen** [comment]
npm i react-native-router-flux@3.38.0 --save

2017-05-09 18:19 GMT+08:00 hama <notifications@github.com>:
